// <auto-generated />
using System;
using AlphaStore.Infrastructure.Database.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlphaStore.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230428143325_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("AlphaStore.Application.Models.Category", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("category", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("AlphaStore.Application.Models.Price", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("REAL")
                        .HasColumnName("amount");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("currency");

                    b.HasKey("Id")
                        .HasName("id");

                    b.ToTable("price", "dbo");
                });

            modelBuilder.Entity("AlphaStore.Application.Models.Product", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CategoryId")
                        .IsRequired()
                        .HasColumnType("INTEGER")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2049)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("file_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<long?>("PriceId")
                        .IsRequired()
                        .HasColumnType("INTEGER")
                        .HasColumnName("price_id");

                    b.Property<int>("Quanitity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("quanitity");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(2)
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PriceId")
                        .IsUnique();

                    b.ToTable("product", "dbo");
                });

            modelBuilder.Entity("AlphaStore.Application.Models.ShoppingCart", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("currency");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("REAL")
                        .HasColumnName("total_price");

                    b.HasKey("Id")
                        .HasName("id");

                    b.ToTable("shopping_cart", "dbo");
                });

            modelBuilder.Entity("AlphaStore.Application.Models.ShoppingCartItem", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ProductId")
                        .IsRequired()
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_id");

                    b.Property<long?>("ShoppingCartId")
                        .IsRequired()
                        .HasColumnType("INTEGER")
                        .HasColumnName("shopping_cart_id");

                    b.HasKey("Id")
                        .HasName("id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShoppingCartId");

                    b.ToTable("shopping_cart_item", "dbo");
                });

            modelBuilder.Entity("AlphaStore.Application.Models.Product", b =>
                {
                    b.HasOne("AlphaStore.Application.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlphaStore.Application.Models.Price", "Price")
                        .WithOne("Product")
                        .HasForeignKey("AlphaStore.Application.Models.Product", "PriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Price");
                });

            modelBuilder.Entity("AlphaStore.Application.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("AlphaStore.Application.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlphaStore.Application.Models.ShoppingCart", "ShoppingCart")
                        .WithMany("Items")
                        .HasForeignKey("ShoppingCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("AlphaStore.Application.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("AlphaStore.Application.Models.Price", b =>
                {
                    b.Navigation("Product")
                        .IsRequired();
                });

            modelBuilder.Entity("AlphaStore.Application.Models.ShoppingCart", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
